// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Pokedex.Repository.Context;
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Pokedex.Repository.Persistence
{
    public partial class Favorites : IObjectState
    {
        [Key]
        public int Id { get; set; }
        public int UserId { get; set; }
        public int PokemonId { get; set; }
        [Required]
        [StringLength(100)]
        public string PokemonName { get; set; }
        [Required]
        [StringLength(100)]
        public string Types { get; set; }
        [Required]
        public byte[] Thumbnail { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DateReg { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateRem { get; set; }

        [ForeignKey(nameof(UserId))]
        [InverseProperty(nameof(Users.Favorites))]
        public virtual Users User { get; set; }

        [NotMapped]
        public ObjectState ObjectState { get; set; }
    }
}